<?php

$announcement_sat = <<<ZZZZZZZZZZ
<table class="info-table">
    <tr>
        <td>{$_->organizer}</td>
        <td>{$_->organizer_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->event_lead}</td>
        <td>{$_->event_lead_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->event_lead_co}</td>
        <td>{$_->event_lead_co_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->course_setter}</td>
        <td>{$_->course_setter_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->judge}</td>
        <td>{$_->judge_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->information}</td>
        <td>{$_->information_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->competition}</td>
        <td>{$_->competition_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->map}</td>
        <td>{$_->map_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->classes}</td>
        <td>{$_->classes_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->event_centre}</td>
        <td>{$_->event_centre_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->access}</td>
        <td>{$_->access_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->route_to_start}</td>
        <td>{$_->route_to_start_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->entry_online}</td>
        <td>{$_->entry_online_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->fees}</td>
        <td>{$_->fees_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->deadline}</td>
        <td>{$_->deadline_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->mutations}</td>
        <td>{$_->mutations_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->start_times}</td>
        <td>{$_->start_times_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->start_order}</td>
        <td>{$_->start_order_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->start_lists}</td>
        <td>{$_->start_lists_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->evaluation}</td>
        <td>{$_->evaluation_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->anti_doping}</td>
        <td>{$_->anti_doping_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->insurance}</td>
        <td>{$_->insurance_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->daycare}</td>
        <td>{$_->daycare_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->childrens_o}</td>
        <td>{$_->childrens_o_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->food}</td>
        <td>{$_->food_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->weekend}</td>
        <td>{$_->weekend_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->program_wcf}</td>
        <td>{$_->program_wcf_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->housing}</td>
        <td>{$_->housing_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->special_remarks}</td>
        <td>{$_->special_remarks_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->early_birds}</td>
        <td>{$_->early_birds_sat_text}</td>
    </tr>
    <!--
        <tr>
            <td>{$_->company}</td>
            <td>{$_->company_sat_text}</td>
        </tr>
    -->
</table>
ZZZZZZZZZZ;

$announcement_sun = <<<ZZZZZZZZZZ
<table class="info-table">
    <tr>
        <td>{$_->organizer}</td>
        <td>{$_->organizer_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->event_lead}</td>
        <td>{$_->event_lead_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->event_lead_co}</td>
        <td>{$_->event_lead_co_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->course_setter}</td>
        <td>{$_->course_setter_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->judge}</td>
        <td>{$_->judge_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->information}</td>
        <td>{$_->information_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->competition}</td>
        <td>{$_->competition_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->map}</td>
        <td>{$_->map_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->classes}</td>
        <td>{$_->classes_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->event_centre}</td>
        <td>{$_->event_centre_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->access}</td>
        <td>{$_->access_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->route_to_start}</td>
        <td>{$_->route_to_start_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->entry_online}</td>
        <td>{$_->entry_online_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->fees}</td>
        <td>{$_->fees_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->deadline}</td>
        <td>{$_->deadline_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->mutations}</td>
        <td>{$_->mutations_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->start_times}</td>
        <td>{$_->start_times_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->start_order}</td>
        <td>{$_->start_order_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->start_lists}</td>
        <td>{$_->start_lists_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->evaluation}</td>
        <td>{$_->evaluation_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->anti_doping}</td>
        <td>{$_->anti_doping_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->insurance}</td>
        <td>{$_->insurance_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->daycare}</td>
        <td>{$_->daycare_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->childrens_o}</td>
        <td>{$_->childrens_o_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->food}</td>
        <td>{$_->food_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->weekend}</td>
        <td>{$_->weekend_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->program_wcf}</td>
        <td>{$_->program_wcf_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->housing}</td>
        <td>{$_->housing_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->special_remarks}</td>
        <td>{$_->special_remarks_sun_text}</td>
    </tr>
</table>
ZZZZZZZZZZ;
