<?php

$course_data_sat_columns = [
    'course',
    'distance',
    'elevation',
    'controls',
    'scale',
    'end_first_third',
    'middle',
    'beginning_last_third',
    'none',
];
$course_data_sat_rows = [
    [
        'course' => 'HE',
        'distance' => '10.6',
        'elevation' => '560',
        'controls' => '26',
        'scale' => '1:10\'000',
        'end_first_third' => 'x',
        'middle' => '',
        'beginning_last_third' => 'x',
        'none' => '',
    ],
    [
        'course' => 'HAL',
        'distance' => '7.7',
        'elevation' => '430',
        'controls' => '17',
        'scale' => '1:10\'000',
        'end_first_third' => '',
        'middle' => '',
        'beginning_last_third' => 'x',
        'none' => '',
    ],
    [
        'course' => 'HAM',
        'distance' => '6.1',
        'elevation' => '260',
        'controls' => '11',
        'scale' => '1:10\'000',
        'end_first_third' => 'x',
        'middle' => '',
        'beginning_last_third' => '',
        'none' => '',
    ],
    [
        'course' => 'HAK',
        'distance' => '4.1',
        'elevation' => '160',
        'controls' => '12',
        'scale' => '1:10\'000',
        'end_first_third' => '',
        'middle' => '',
        'beginning_last_third' => '',
        'none' => 'x',
    ],
    [
        'course' => 'HB',
        'distance' => '4.3',
        'elevation' => '190',
        'controls' => '11',
        'scale' => '1:10\'000',
        'end_first_third' => '',
        'middle' => '',
        'beginning_last_third' => 'x',
        'none' => '',
    ],
    [
        'course' => 'H35',
        'distance' => '6.1',
        'elevation' => '290',
        'controls' => '15',
        'scale' => '1:10\'000',
        'end_first_third' => 'x',
        'middle' => '',
        'beginning_last_third' => '',
        'none' => '',
    ],
    [
        'course' => 'H40',
        'distance' => '6.3',
        'elevation' => '270',
        'controls' => '14',
        'scale' => '1:10\'000',
        'end_first_third' => 'x',
        'middle' => '',
        'beginning_last_third' => '',
        'none' => '',
    ],
    [
        'course' => 'H45',
        'distance' => '6.2',
        'elevation' => '290',
        'controls' => '16',
        'scale' => '1:10\'000',
        'end_first_third' => 'x',
        'middle' => '',
        'beginning_last_third' => '',
        'none' => '',
    ],
    [
        'course' => 'H50',
        'distance' => '6.2',
        'elevation' => '270',
        'controls' => '15',
        'scale' => '1:7\'500',
        'end_first_third' => 'x',
        'middle' => '',
        'beginning_last_third' => 'x',
        'none' => '',
    ],
    [
        'course' => 'H55',
        'distance' => '6.1',
        'elevation' => '260',
        'controls' => '14',
        'scale' => '1:7\'500',
        'end_first_third' => '',
        'middle' => '',
        'beginning_last_third' => 'x',
        'none' => '',
    ],
    [
        'course' => 'H60',
        'distance' => '5.5',
        'elevation' => '200',
        'controls' => '12',
        'scale' => '1:7\'500',
        'end_first_third' => '',
        'middle' => 'x',
        'beginning_last_third' => '',
        'none' => '',
    ],
    [
        'course' => 'H65',
        'distance' => '5.0',
        'elevation' => '220',
        'controls' => '14',
        'scale' => '1:7\'500',
        'end_first_third' => 'x',
        'middle' => '',
        'beginning_last_third' => '',
        'none' => '',
    ],
    [
        'course' => 'H70',
        'distance' => '4.8',
        'elevation' => '160',
        'controls' => '12',
        'scale' => '1:7\'500',
        'end_first_third' => '',
        'middle' => 'x',
        'beginning_last_third' => '',
        'none' => '',
    ],
    [
        'course' => 'H75',
        'distance' => '4.2',
        'elevation' => '150',
        'controls' => '12',
        'scale' => '1:7\'500',
        'end_first_third' => '',
        'middle' => '',
        'beginning_last_third' => 'x',
        'none' => '',
    ],
    [
        'course' => 'H80',
        'distance' => '3.5',
        'elevation' => '80',
        'controls' => '10',
        'scale' => '1:7\'500',
        'end_first_third' => '',
        'middle' => '',
        'beginning_last_third' => '',
        'none' => 'x',
    ],
    [
        'course' => 'H85',
        'distance' => '3.2',
        'elevation' => '80',
        'controls' => '10',
        'scale' => '1:7\'500',
        'end_first_third' => '',
        'middle' => '',
        'beginning_last_third' => '',
        'none' => 'x',
    ],
    [
        'course' => 'H20',
        'distance' => '8.5',
        'elevation' => '480',
        'controls' => '22',
        'scale' => '1:10\'000',
        'end_first_third' => 'x',
        'middle' => '',
        'beginning_last_third' => 'x',
        'none' => '',
    ],
    [
        'course' => 'H18',
        'distance' => '7.3',
        'elevation' => '340',
        'controls' => '16',
        'scale' => '1:10\'000',
        'end_first_third' => 'x',
        'middle' => '',
        'beginning_last_third' => 'x',
        'none' => '',
    ],
    [
        'course' => 'H16',
        'distance' => '6.0',
        'elevation' => '280',
        'controls' => '14',
        'scale' => '1:10\'000',
        'end_first_third' => '',
        'middle' => '',
        'beginning_last_third' => 'x',
        'none' => '',
    ],
    [
        'course' => 'H14',
        'distance' => '4.7',
        'elevation' => '220',
        'controls' => '16',
        'scale' => '1:10\'000',
        'end_first_third' => '',
        'middle' => '',
        'beginning_last_third' => 'x',
        'none' => '',
    ],
    [
        'course' => 'H12',
        'distance' => '3.3',
        'elevation' => '160',
        'controls' => '13',
        'scale' => '1:10\'000',
        'end_first_third' => '',
        'middle' => '',
        'beginning_last_third' => '',
        'none' => 'x',
    ],
    [
        'course' => 'H10',
        'distance' => '2.2',
        'elevation' => '60',
        'controls' => '8',
        'scale' => '1:10\'000',
        'end_first_third' => '',
        'middle' => '',
        'beginning_last_third' => '',
        'none' => 'x',
    ],
    [
        'course' => 'DE',
        'distance' => '7.4',
        'elevation' => '340',
        'controls' => '20',
        'scale' => '1:10\'000',
        'end_first_third' => '',
        'middle' => '',
        'beginning_last_third' => 'x',
        'none' => '',
    ],
    [
        'course' => 'DAL',
        'distance' => '5.2',
        'elevation' => '250',
        'controls' => '11',
        'scale' => '1:10\'000',
        'end_first_third' => '',
        'middle' => '',
        'beginning_last_third' => 'x',
        'none' => '',
    ],
    [
        'course' => 'DAM',
        'distance' => '4.9',
        'elevation' => '170',
        'controls' => '14',
        'scale' => '1:10\'000',
        'end_first_third' => '',
        'middle' => '',
        'beginning_last_third' => 'x',
        'none' => '',
    ],
    [
        'course' => 'DAK',
        'distance' => '3.1',
        'elevation' => '140',
        'controls' => '9',
        'scale' => '1:10\'000',
        'end_first_third' => '',
        'middle' => '',
        'beginning_last_third' => '',
        'none' => 'x',
    ],
    [
        'course' => 'DB',
        'distance' => '2.9',
        'elevation' => '130',
        'controls' => '9',
        'scale' => '1:10\'000',
        'end_first_third' => '',
        'middle' => '',
        'beginning_last_third' => '',
        'none' => 'x',
    ],
    [
        'course' => 'D35',
        'distance' => '5.2',
        'elevation' => '210',
        'controls' => '12',
        'scale' => '1:10\'000',
        'end_first_third' => 'x',
        'middle' => '',
        'beginning_last_third' => 'x',
        'none' => '',
    ],
    [
        'course' => 'D40',
        'distance' => '5.0',
        'elevation' => '250',
        'controls' => '10',
        'scale' => '1:10\'000',
        'end_first_third' => 'x',
        'middle' => '',
        'beginning_last_third' => '',
        'none' => '',
    ],
    [
        'course' => 'D45',
        'distance' => '4.8',
        'elevation' => '220',
        'controls' => '11',
        'scale' => '1:10\'000',
        'end_first_third' => '',
        'middle' => 'x',
        'beginning_last_third' => '',
        'none' => '',
    ],
    [
        'course' => 'D50',
        'distance' => '5.3',
        'elevation' => '190',
        'controls' => '12',
        'scale' => '1:7\'500',
        'end_first_third' => '',
        'middle' => '',
        'beginning_last_third' => 'x',
        'none' => '',
    ],
    [
        'course' => 'D55',
        'distance' => '4.6',
        'elevation' => '210',
        'controls' => '10',
        'scale' => '1:7\'500',
        'end_first_third' => '',
        'middle' => '',
        'beginning_last_third' => 'x',
        'none' => '',
    ],
    [
        'course' => 'D60',
        'distance' => '5.0',
        'elevation' => '180',
        'controls' => '12',
        'scale' => '1:7\'500',
        'end_first_third' => '',
        'middle' => 'x',
        'beginning_last_third' => 'x',
        'none' => '',
    ],
    [
        'course' => 'D65',
        'distance' => '4.9',
        'elevation' => '160',
        'controls' => '13',
        'scale' => '1:7\'500',
        'end_first_third' => '',
        'middle' => '',
        'beginning_last_third' => 'x',
        'none' => '',
    ],
    [
        'course' => 'D70',
        'distance' => '3.9',
        'elevation' => '150',
        'controls' => '12',
        'scale' => '1:7\'500',
        'end_first_third' => '',
        'middle' => '',
        'beginning_last_third' => 'x',
        'none' => '',
    ],
    [
        'course' => 'D75',
        'distance' => '3.0',
        'elevation' => '70',
        'controls' => '8',
        'scale' => '1:7\'500',
        'end_first_third' => '',
        'middle' => '',
        'beginning_last_third' => '',
        'none' => 'x',
    ],
    [
        'course' => 'D80',
        'distance' => '2.6',
        'elevation' => '60',
        'controls' => '7',
        'scale' => '1:7\'500',
        'end_first_third' => '',
        'middle' => '',
        'beginning_last_third' => '',
        'none' => 'x',
    ],
    [
        'course' => 'D20',
        'distance' => '5.7',
        'elevation' => '250',
        'controls' => '14',
        'scale' => '1:10\'000',
        'end_first_third' => '',
        'middle' => '',
        'beginning_last_third' => 'x',
        'none' => '',
    ],
    [
        'course' => 'D18',
        'distance' => '5.5',
        'elevation' => '200',
        'controls' => '11',
        'scale' => '1:10\'000',
        'end_first_third' => '',
        'middle' => 'x',
        'beginning_last_third' => '',
        'none' => '',
    ],
    [
        'course' => 'D16',
        'distance' => '5.1',
        'elevation' => '200',
        'controls' => '13',
        'scale' => '1:10\'000',
        'end_first_third' => '',
        'middle' => 'x',
        'beginning_last_third' => '',
        'none' => '',
    ],
    [
        'course' => 'D14',
        'distance' => '4.3',
        'elevation' => '160',
        'controls' => '14',
        'scale' => '1:10\'000',
        'end_first_third' => '',
        'middle' => '',
        'beginning_last_third' => 'x',
        'none' => '',
    ],
    [
        'course' => 'D12',
        'distance' => '2.9',
        'elevation' => '150',
        'controls' => '11',
        'scale' => '1:10\'000',
        'end_first_third' => '',
        'middle' => '',
        'beginning_last_third' => '',
        'none' => 'x',
    ],
    [
        'course' => 'D10',
        'distance' => '2.2',
        'elevation' => '60',
        'controls' => '8',
        'scale' => '1:10\'000',
        'end_first_third' => '',
        'middle' => '',
        'beginning_last_third' => '',
        'none' => 'x',
    ],
    [
        'course' => 'OL',
        'distance' => '4.0',
        'elevation' => '170',
        'controls' => '7',
        'scale' => '1:10\'000',
        'end_first_third' => '',
        'middle' => '',
        'beginning_last_third' => '',
        'none' => 'x',
    ],
    [
        'course' => 'OM',
        'distance' => '3.5',
        'elevation' => '110',
        'controls' => '7',
        'scale' => '1:10\'000',
        'end_first_third' => '',
        'middle' => '',
        'beginning_last_third' => '',
        'none' => 'x',
    ],
    [
        'course' => 'OK',
        'distance' => '2.2',
        'elevation' => '70',
        'controls' => '5',
        'scale' => '1:10\'000',
        'end_first_third' => '',
        'middle' => '',
        'beginning_last_third' => '',
        'none' => 'x',
    ],
    [
        'course' => 'sCOOL',
        'distance' => '2.1',
        'elevation' => '60',
        'controls' => '7',
        'scale' => '1:10\'000',
        'end_first_third' => '',
        'middle' => '',
        'beginning_last_third' => '',
        'none' => 'x',
    ],
];

$course_data_sun_columns = [
    'course',
    'distance',
    'elevation',
    'controls',
    'scale',
];
$course_data_sun_rows = [
    [
        'course' => 'HE',
        'distance' => '5.4',
        'elevation' => '240',
        'controls' => '22',
        'scale' => '1:10\'000',
    ],
    [
        'course' => 'HAL',
        'distance' => '5.1',
        'elevation' => '225',
        'controls' => '18',
        'scale' => '1:10\'000',
    ],
    [
        'course' => 'HAM',
        'distance' => '3.7',
        'elevation' => '160',
        'controls' => '14',
        'scale' => '1:10\'000',
    ],
    [
        'course' => 'HAK',
        'distance' => '3.5',
        'elevation' => '120',
        'controls' => '13',
        'scale' => '1:10\'000',
    ],
    [
        'course' => 'HB',
        'distance' => '3.2',
        'elevation' => '120',
        'controls' => '12',
        'scale' => '1:10\'000',
    ],
    [
        'course' => 'H35',
        'distance' => '4.1',
        'elevation' => '175',
        'controls' => '16',
        'scale' => '1:10\'000',
    ],
    [
        'course' => 'H40',
        'distance' => '3.9',
        'elevation' => '155',
        'controls' => '15',
        'scale' => '1:10\'000',
    ],
    [
        'course' => 'H45',
        'distance' => '4.0',
        'elevation' => '160',
        'controls' => '16',
        'scale' => '1:10\'000',
    ],
    [
        'course' => 'H50',
        'distance' => '4.0',
        'elevation' => '175',
        'controls' => '16',
        'scale' => '1:7\'500',
    ],
    [
        'course' => 'H55',
        'distance' => '3.8',
        'elevation' => '145',
        'controls' => '15',
        'scale' => '1:7\'500',
    ],
    [
        'course' => 'H60',
        'distance' => '3.6',
        'elevation' => '155',
        'controls' => '15',
        'scale' => '1:7\'500',
    ],
    [
        'course' => 'H65',
        'distance' => '3.3',
        'elevation' => '110',
        'controls' => '14',
        'scale' => '1:7\'500',
    ],
    [
        'course' => 'H70',
        'distance' => '3.2',
        'elevation' => '105',
        'controls' => '12',
        'scale' => '1:7\'500',
    ],
    [
        'course' => 'H75',
        'distance' => '2.8',
        'elevation' => '105',
        'controls' => '12',
        'scale' => '1:7\'500',
    ],
    [
        'course' => 'H80',
        'distance' => '2.1',
        'elevation' => '60',
        'controls' => '10',
        'scale' => '1:7\'500',
    ],
    [
        'course' => 'H85',
        'distance' => '2.1',
        'elevation' => '60',
        'controls' => '9',
        'scale' => '1:7\'500',
    ],
    [
        'course' => 'H20',
        'distance' => '5.1',
        'elevation' => '235',
        'controls' => '18',
        'scale' => '1:10\'000',
    ],
    [
        'course' => 'H18',
        'distance' => '4.7',
        'elevation' => '160',
        'controls' => '18',
        'scale' => '1:10\'000',
    ],
    [
        'course' => 'H16',
        'distance' => '3.9',
        'elevation' => '180',
        'controls' => '18',
        'scale' => '1:10\'000',
    ],
    [
        'course' => 'H14',
        'distance' => '3.2',
        'elevation' => '125',
        'controls' => '13',
        'scale' => '1:10\'000',
    ],
    [
        'course' => 'H12',
        'distance' => '2.9',
        'elevation' => '75',
        'controls' => '13',
        'scale' => '1:10\'000',
    ],
    [
        'course' => 'H10',
        'distance' => '2.2',
        'elevation' => '40',
        'controls' => '10',
        'scale' => '1:10\'000',
    ],
    [
        'course' => 'DE',
        'distance' => '3.8',
        'elevation' => '185',
        'controls' => '16',
        'scale' => '1:10\'000',
    ],
    [
        'course' => 'DAL',
        'distance' => '3.7',
        'elevation' => '140',
        'controls' => '16',
        'scale' => '1:10\'000',
    ],
    [
        'course' => 'DAM',
        'distance' => '3.5',
        'elevation' => '130',
        'controls' => '14',
        'scale' => '1:10\'000',
    ],
    [
        'course' => 'DAK',
        'distance' => '2.7',
        'elevation' => '105',
        'controls' => '13',
        'scale' => '1:10\'000',
    ],
    [
        'course' => 'DB',
        'distance' => '2.6',
        'elevation' => '60',
        'controls' => '13',
        'scale' => '1:10\'000',
    ],
    [
        'course' => 'D35',
        'distance' => '3.5',
        'elevation' => '115',
        'controls' => '15',
        'scale' => '1:10\'000',
    ],
    [
        'course' => 'D40',
        'distance' => '3.6',
        'elevation' => '150',
        'controls' => '14',
        'scale' => '1:10\'000',
    ],
    [
        'course' => 'D45',
        'distance' => '3.4',
        'elevation' => '130',
        'controls' => '15',
        'scale' => '1:10\'000',
    ],
    [
        'course' => 'D50',
        'distance' => '3.7',
        'elevation' => '145',
        'controls' => '15',
        'scale' => '1:7\'500',
    ],
    [
        'course' => 'D55',
        'distance' => '3.4',
        'elevation' => '120',
        'controls' => '13',
        'scale' => '1:7\'500',
    ],
    [
        'course' => 'D60',
        'distance' => '3.1',
        'elevation' => '115',
        'controls' => '14',
        'scale' => '1:7\'500',
    ],
    [
        'course' => 'D65',
        'distance' => '2.6',
        'elevation' => '95',
        'controls' => '12',
        'scale' => '1:7\'500',
    ],
    [
        'course' => 'D70',
        'distance' => '2.6',
        'elevation' => '90',
        'controls' => '11',
        'scale' => '1:7\'500',
    ],
    [
        'course' => 'D75',
        'distance' => '2.1',
        'elevation' => '105',
        'controls' => '10',
        'scale' => '1:7\'500',
    ],
    [
        'course' => 'D80',
        'distance' => '2.2',
        'elevation' => '60',
        'controls' => '9',
        'scale' => '1:7\'500',
    ],
    [
        'course' => 'D20',
        'distance' => '3.8',
        'elevation' => '145',
        'controls' => '17',
        'scale' => '1:10\'000',
    ],
    [
        'course' => 'D18',
        'distance' => '3.6',
        'elevation' => '150',
        'controls' => '15',
        'scale' => '1:10\'000',
    ],
    [
        'course' => 'D16',
        'distance' => '3.4',
        'elevation' => '120',
        'controls' => '15',
        'scale' => '1:10\'000',
    ],
    [
        'course' => 'D14',
        'distance' => '3.2',
        'elevation' => '125',
        'controls' => '16',
        'scale' => '1:10\'000',
    ],
    [
        'course' => 'D12',
        'distance' => '2.8',
        'elevation' => '75',
        'controls' => '12',
        'scale' => '1:10\'000',
    ],
    [
        'course' => 'D10',
        'distance' => '2.2',
        'elevation' => '40',
        'controls' => '9',
        'scale' => '1:10\'000',
    ],
    [
        'course' => 'OL',
        'distance' => '4.1',
        'elevation' => '155',
        'controls' => '17',
        'scale' => '1:10\'000',
    ],
    [
        'course' => 'OM',
        'distance' => '3.2',
        'elevation' => '110',
        'controls' => '16',
        'scale' => '1:10\'000',
    ],
    [
        'course' => 'OK',
        'distance' => '2.2',
        'elevation' => '40',
        'controls' => '10',
        'scale' => '1:10\'000',
    ],
    [
        'course' => 'sCOOL',
        'distance' => '',
        'elevation' => '',
        'controls' => '',
        'scale' => 'Beim Kinder OL',
    ],
];

function render_course_data($rows, $columns) {
    global $_;
    $out = '<table class="course-data">';
    $out .= '<tr>';
    foreach ($columns as $column) {
        $translation_key = "course_data_{$column}";
        $column_title = $_->{$translation_key};
        $out .= "<th>{$column_title}</th>";
    }
    $out .= '</tr>';
    foreach ($rows as $row) {
        $out .= '</tr>';
        foreach ($columns as $column) {
            $cell_data = $row[$column];
            $prefix_key = "course_data_{$column}_prefix";
            $prefix = $_->{$prefix_key};
            $suffix_key = "course_data_{$column}_suffix";
            $suffix = $_->{$suffix_key};
            $out .= "<td>{$prefix}{$cell_data}{$suffix}</td>";
        }
        $out .= '</tr>';
    }
    $out .= '</table>';
    return $out;
}

$course_data_sat = render_course_data($course_data_sat_rows, $course_data_sat_columns);
$course_data_sun = render_course_data($course_data_sun_rows, $course_data_sun_columns);
