<?php

$directives_sat = <<<ZZZZZZZZZZ
<table class="info-table">
    <tr>
        <td>{$_->briefing}</td>
        <td>{$_->briefing_sat_text}</td>
    </tr>
    <tr>
        <td colspan="2">
            {$_->access_sat_img}
        </td>
    </tr>
    <tr>
        <td>{$_->organizer}</td>
        <td>{$_->organizer_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->event_lead}</td>
        <td>{$_->event_lead_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->event_lead_co}</td>
        <td>{$_->event_lead_co_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->course_setter}</td>
        <td>{$_->course_setter_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->judge}</td>
        <td>{$_->judge_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->arbitration}</td>
        <td>{$_->arbitration_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->information}</td>
        <td>{$_->information_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->competition}</td>
        <td>{$_->competition_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->map}</td>
        <td>{$_->map_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->map_symbols}</td>
        <td>{$_->map_symbols_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->terrain_directives}</td>
        <td>{$_->terrain_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->forbidden_area}</td>
        <td>{$_->forbidden_area_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->event_centre}</td>
        <td>{$_->event_centre_sat_text}</td>
    </tr>
    <tr>
        <td colspan="2">
            {$_->event_centre_sat_img}
        </td>
    </tr>
    <tr>
        <td>{$_->information_evaluation}</td>
        <td>{$_->information_evaluation_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->access}</td>
        <td>{$_->access_directives_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->entry_open}</td>
        <td>{$_->entry_open_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->fees}</td>
        <td>{$_->fees_directives_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->deadline}</td>
        <td>{$_->deadline_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->mutations}</td>
        <td>{$_->mutations_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->start_times}</td>
        <td>{$_->start_times_directives_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->start_order}</td>
        <td>{$_->start_order_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->start_lists}</td>
        <td>{$_->start_lists_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->route_to_start}</td>
        <td>{$_->route_to_start_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->start_procedure}</td>
        <td>{$_->start_procedure_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->courses}</td>
        <td>{$_->courses_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->course_control}</td>
        <td>{$_->course_control_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->maximum_time}</td>
        <td>{$_->maximum_time_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->complaints}</td>
        <td>{$_->complaints_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->drinking_point}</td>
        <td>{$_->drinking_point_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->clothing_transport}</td>
        <td>{$_->clothing_transport_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->cancellation}</td>
        <td>{$_->cancellation_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->ambulance}</td>
        <td>{$_->ambulance_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->anti_doping}</td>
        <td>{$_->anti_doping_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->insurance}</td>
        <td>{$_->insurance_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->results}</td>
        <td>{$_->results_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->route_gadget}</td>
        <td>{$_->route_gadget_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->map_return}</td>
        <td>{$_->map_return_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->forfeit}</td>
        <td>{$_->forfeit_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->daycare}</td>
        <td>{$_->daycare_directives_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->childrens_o_string_o}</td>
        <td>{$_->childrens_o_directives_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->toilets}</td>
        <td>{$_->toilets_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->food}</td>
        <td>{$_->food_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->weekend}</td>
        <td>{$_->weekend_directives_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->program_wcf}</td>
        <td>{$_->program_wcf_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->special_remarks}</td>
        <td>{$_->special_remarks_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->early_birds}</td>
        <td>{$_->early_birds_sat_text}</td>
    </tr>
    <tr>
        <td>{$_->alternative_returns}</td>
        <td>{$_->alternative_returns_sat_text}</td>
    </tr>
</table>
ZZZZZZZZZZ;

$directives_sun = <<<ZZZZZZZZZZ
<table class="info-table">
    <tr>
        <td>{$_->briefing}</td>
        <td>{$_->briefing_sun_text}</td>
    </tr>
    <tr>
        <td colspan="2">
            {$_->access_sun_img}
        </td>
    </tr>
    <tr>
        <td>{$_->organizer}</td>
        <td>{$_->organizer_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->event_lead}</td>
        <td>{$_->event_lead_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->event_lead_co}</td>
        <td>{$_->event_lead_co_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->course_setter}</td>
        <td>{$_->course_setter_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->judge}</td>
        <td>{$_->judge_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->land_use}</td>
        <td>{$_->land_use_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->arbitration}</td>
        <td>{$_->arbitration_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->information}</td>
        <td>{$_->information_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->competition}</td>
        <td>{$_->competition_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->map}</td>
        <td>{$_->map_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->terrain_directives}</td>
        <td>{$_->terrain_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->forbidden_area}</td>
        <td>{$_->forbidden_area_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->event_centre}</td>
        <td>{$_->event_centre_sun_text}</td>
    </tr>
    <tr>
        <td colspan="2">
            {$_->event_centre_sun_img}
        </td>
    </tr>
    <tr>
        <td>{$_->information_evaluation}</td>
        <td>{$_->information_evaluation_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->access}</td>
        <td>{$_->access_directives_sun_text}</td>
    </tr>
    <tr>
        <td colspan="2">
            {$_->overview_sun_img}
        </td>
    </tr>
    <tr>
        <td>{$_->return}</td>
        <td>{$_->return_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->route_to_start}</td>
        <td>{$_->route_to_start_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->entry_open}</td>
        <td>{$_->entry_open_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->fees}</td>
        <td>{$_->fees_directives_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->deadline}</td>
        <td>{$_->deadline_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->mutations}</td>
        <td>{$_->mutations_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->start_times}</td>
        <td>{$_->start_times_directives_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->start_order}</td>
        <td>{$_->start_order_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->start_lists}</td>
        <td>{$_->start_lists_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->start_procedure}</td>
        <td>{$_->start_procedure_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->courses}</td>
        <td>{$_->courses_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->course_control}</td>
        <td>{$_->course_control_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->maximum_time}</td>
        <td>{$_->maximum_time_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->complaints}</td>
        <td>{$_->complaints_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->clothing_transport}</td>
        <td>{$_->clothing_transport_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->cancellation}</td>
        <td>{$_->cancellation_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->ambulance}</td>
        <td>{$_->ambulance_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->anti_doping}</td>
        <td>{$_->anti_doping_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->insurance}</td>
        <td>{$_->insurance_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->results}</td>
        <td>{$_->results_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->route_gadget}</td>
        <td>{$_->route_gadget_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->map_return}</td>
        <td>{$_->map_return_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->forfeit}</td>
        <td>{$_->forfeit_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->daycare}</td>
        <td>{$_->daycare_directives_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->childrens_o}</td>
        <td>{$_->childrens_o_directives_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->toilets}</td>
        <td>{$_->toilets_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->food}</td>
        <td>{$_->food_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->local_food}</td>
        <td>{$_->local_food_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->weekend}</td>
        <td>{$_->weekend_directives_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->program_wcf}</td>
        <td>{$_->program_wcf_sun_text}</td>
    </tr>
    <tr>
        <td>{$_->special_remarks}</td>
        <td>{$_->special_remarks_sun_text}</td>
    </tr>
</table>
ZZZZZZZZZZ;
