framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope: 
            sender: '%env(MAILER_ENVELOPE_SENDER)%'
        headers:
            From: 'OL Zimmerberg<%env(MAILER_ENVELOPE_SENDER)%>'