<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20230918231338 extends AbstractMigration {
    public function getDescription(): string {
        return 'Rename aktuell to news, remove old tables';
    }

    public function up(Schema $schema): void {
        $this->addSql('CREATE TABLE news (id INT AUTO_INCREMENT NOT NULL, author_user_id INT DEFAULT NULL, author_role_id INT DEFAULT NULL, owner_user_id INT DEFAULT NULL, owner_role_id INT DEFAULT NULL, created_by_user_id INT DEFAULT NULL, last_modified_by_user_id INT DEFAULT NULL, termin INT NOT NULL, published_date DATE NOT NULL, published_time TIME DEFAULT NULL, newsletter TINYINT(1) DEFAULT 1 NOT NULL, title LONGTEXT NOT NULL, teaser LONGTEXT DEFAULT NULL, content LONGTEXT DEFAULT NULL, image_ids LONGTEXT DEFAULT NULL, external_url LONGTEXT DEFAULT NULL, author_name VARCHAR(255) DEFAULT NULL, author_email VARCHAR(255) DEFAULT NULL, format LONGTEXT NOT NULL, tags LONGTEXT DEFAULT \'\' NOT NULL, bild1 LONGTEXT DEFAULT NULL, bild1_breite INT DEFAULT NULL, bild1_text LONGTEXT DEFAULT NULL, bild2 LONGTEXT DEFAULT NULL, bild2_breite INT DEFAULT NULL, bild3 LONGTEXT DEFAULT NULL, bild3_breite INT DEFAULT NULL, zeit TIME DEFAULT NULL, counter INT DEFAULT 0 NOT NULL, on_off INT DEFAULT 1 NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, last_modified_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX IDX_1DD39950E2544CD6 (author_user_id), INDEX IDX_1DD399509339BDEF (author_role_id), INDEX IDX_1DD399502B18554A (owner_user_id), INDEX IDX_1DD399505A75A473 (owner_role_id), INDEX IDX_1DD399507D182D95 (created_by_user_id), INDEX IDX_1DD399501A04EF5A (last_modified_by_user_id), INDEX published_index (published_date, published_time), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE news ADD CONSTRAINT FK_1DD39950E2544CD6 FOREIGN KEY (author_user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE news ADD CONSTRAINT FK_1DD399509339BDEF FOREIGN KEY (author_role_id) REFERENCES roles (id)');
        $this->addSql('ALTER TABLE news ADD CONSTRAINT FK_1DD399502B18554A FOREIGN KEY (owner_user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE news ADD CONSTRAINT FK_1DD399505A75A473 FOREIGN KEY (owner_role_id) REFERENCES roles (id)');
        $this->addSql('ALTER TABLE news ADD CONSTRAINT FK_1DD399507D182D95 FOREIGN KEY (created_by_user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE news ADD CONSTRAINT FK_1DD399501A04EF5A FOREIGN KEY (last_modified_by_user_id) REFERENCES users (id)');
        $this->addSql('INSERT INTO news (id, author_user_id, author_role_id, owner_user_id, owner_role_id, created_by_user_id, last_modified_by_user_id, termin, published_date, published_time, newsletter, title, teaser, content, image_ids, external_url, author_name, author_email, format, tags, bild1, bild1_breite, bild1_text, bild2, bild2_breite, bild3, bild3_breite, zeit, counter, on_off, created_at, last_modified_at) SELECT id, author_user_id, author_role_id, owner_user_id, owner_role_id, created_by_user_id, last_modified_by_user_id, termin, published_date, published_time, newsletter, title, teaser, content, image_ids, external_url, author_name, author_email, format, tags, bild1, bild1_breite, bild1_text, bild2, bild2_breite, bild3, bild3_breite, zeit, counter, on_off, created_at, last_modified_at FROM aktuell');
        $this->addSql('ALTER TABLE aktuell DROP FOREIGN KEY FK_417D71041A04EF5A');
        $this->addSql('ALTER TABLE aktuell DROP FOREIGN KEY FK_417D71047D182D95');
        $this->addSql('ALTER TABLE aktuell DROP FOREIGN KEY FK_417D71042B18554A');
        $this->addSql('ALTER TABLE aktuell DROP FOREIGN KEY FK_417D71049339BDEF');
        $this->addSql('ALTER TABLE aktuell DROP FOREIGN KEY FK_417D71045A75A473');
        $this->addSql('ALTER TABLE aktuell DROP FOREIGN KEY FK_417D7104E2544CD6');
        $this->addSql('DROP TABLE aktuell');
        $this->addSql('DROP TABLE blog');
        $this->addSql('DROP TABLE forum');
        $this->addSql('DROP TABLE galerie');
    }

    public function down(Schema $schema): void {
        $this->addSql('CREATE TABLE aktuell (id INT AUTO_INCREMENT NOT NULL, author_user_id INT DEFAULT NULL, author_role_id INT DEFAULT NULL, owner_user_id INT DEFAULT NULL, owner_role_id INT DEFAULT NULL, created_by_user_id INT DEFAULT NULL, last_modified_by_user_id INT DEFAULT NULL, format LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, published_date DATE NOT NULL, published_time TIME DEFAULT NULL, title LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, teaser LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, content LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, author_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, author_email VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, termin INT NOT NULL, external_url LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, on_off INT DEFAULT 1 NOT NULL, bild1 LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, bild1_breite INT DEFAULT NULL, bild1_text LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, bild2 LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, bild2_breite INT DEFAULT NULL, bild3 LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, bild3_breite INT DEFAULT NULL, zeit TIME DEFAULT NULL, counter INT DEFAULT 0 NOT NULL, tags LONGTEXT CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, last_modified_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, image_ids LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, newsletter TINYINT(1) DEFAULT 1 NOT NULL, INDEX published_index (published_date, published_time), INDEX IDX_417D71045A75A473 (owner_role_id), INDEX IDX_417D7104E2544CD6 (author_user_id), INDEX IDX_417D71047D182D95 (created_by_user_id), INDEX IDX_417D71049339BDEF (author_role_id), INDEX IDX_417D71041A04EF5A (last_modified_by_user_id), INDEX IDX_417D71042B18554A (owner_user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE blog (id INT AUTO_INCREMENT NOT NULL, counter INT DEFAULT 0 NOT NULL, datum DATE DEFAULT NULL, autor LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, titel LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, text LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, bild1 LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, bild2 LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, on_off INT DEFAULT NULL, zeit TIME DEFAULT NULL, dummy INT DEFAULT NULL, file1 LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, file1_name LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, file2 LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, file2_name LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, bild1_breite INT DEFAULT NULL, bild2_breite INT DEFAULT NULL, linkext LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, newsletter TINYINT(1) DEFAULT 1 NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE forum (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_ci`, email VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, eintrag LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, uid VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_ci`, datum DATE DEFAULT NULL, zeit TIME DEFAULT NULL, on_off INT DEFAULT NULL, allow_html INT DEFAULT NULL, name2 VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_ci`, newsletter TINYINT(1) DEFAULT 1 NOT NULL, INDEX datum_on_off_index (datum, on_off), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE galerie (id INT AUTO_INCREMENT NOT NULL, termin INT NOT NULL, titel LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, datum DATE DEFAULT NULL, datum_end DATE DEFAULT NULL, autor LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, on_off INT DEFAULT 0 NOT NULL, typ LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, counter INT DEFAULT NULL, content LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, INDEX datum_on_off_index (datum, on_off), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('ALTER TABLE aktuell ADD CONSTRAINT FK_417D71041A04EF5A FOREIGN KEY (last_modified_by_user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE aktuell ADD CONSTRAINT FK_417D71047D182D95 FOREIGN KEY (created_by_user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE aktuell ADD CONSTRAINT FK_417D71042B18554A FOREIGN KEY (owner_user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE aktuell ADD CONSTRAINT FK_417D71049339BDEF FOREIGN KEY (author_role_id) REFERENCES roles (id)');
        $this->addSql('ALTER TABLE aktuell ADD CONSTRAINT FK_417D71045A75A473 FOREIGN KEY (owner_role_id) REFERENCES roles (id)');
        $this->addSql('ALTER TABLE aktuell ADD CONSTRAINT FK_417D7104E2544CD6 FOREIGN KEY (author_user_id) REFERENCES users (id)');
        $this->addSql('INSERT INTO aktuell (id, author_user_id, author_role_id, owner_user_id, owner_role_id, created_by_user_id, last_modified_by_user_id, termin, published_date, published_time, newsletter, title, teaser, content, image_ids, external_url, author_name, author_email, format, tags, bild1, bild1_breite, bild1_text, bild2, bild2_breite, bild3, bild3_breite, zeit, counter, on_off, created_at, last_modified_at) SELECT id, author_user_id, author_role_id, owner_user_id, owner_role_id, created_by_user_id, last_modified_by_user_id, termin, published_date, published_time, newsletter, title, teaser, content, image_ids, external_url, author_name, author_email, format, tags, bild1, bild1_breite, bild1_text, bild2, bild2_breite, bild3, bild3_breite, zeit, counter, on_off, created_at, last_modified_at FROM news');
        $this->addSql('ALTER TABLE news DROP FOREIGN KEY FK_1DD39950E2544CD6');
        $this->addSql('ALTER TABLE news DROP FOREIGN KEY FK_1DD399509339BDEF');
        $this->addSql('ALTER TABLE news DROP FOREIGN KEY FK_1DD399502B18554A');
        $this->addSql('ALTER TABLE news DROP FOREIGN KEY FK_1DD399505A75A473');
        $this->addSql('ALTER TABLE news DROP FOREIGN KEY FK_1DD399507D182D95');
        $this->addSql('ALTER TABLE news DROP FOREIGN KEY FK_1DD399501A04EF5A');
        $this->addSql('DROP TABLE news');
    }
}
