controllers:
    resource: ../src/Controller/
    type: annotation

app_controllers:
    resource: ../src/Apps/*/*Controller.php
    type: annotation

artgris_bundle_file_manager:
    resource: "@ArtgrisFileManagerBundle/Controller"
    type:     annotation
    prefix:   /apps/files

kernel:
    resource: ../src/Kernel.php
    type: annotation
