controllers:
    resource: 
        path: ../src/Controller/
        namespace: Olz\Controller
    type: annotation

app_controllers:
    resource: ../src/Apps/*/*Controller.php
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
