services:
    _defaults:
        public: true

    Olz\News\Utils\NewsFilterUtils:
        public: true

    Olz\Termine\Utils\TermineFilterUtils:
        public: true

    Olz\Tests\IntegrationTests\Utils\HttpUtilsForIntegrationTest:
        public: true

    Olz\Tests\IntegrationTests\Utils\FakeIntegrationTestDbUtils:
        public: true

    Olz\Tests\IntegrationTests\Utils\WithUtilsTraitIntegrationClassWithUtilsTrait:
        public: true
