# Skript, um die farbkorrigierten, originalgrossen Bilder für die "Für Einsteiger" Seite zu generieren

convert -auto-level -normalize -resize "800>" ./originals/ansprechperson_001.jpg ./img/ansprechperson_001.jpg
convert -auto-level -normalize -resize "800>" ./originals/ansprechperson_002.jpg ./img/ansprechperson_002.jpg
convert -auto-level -normalize -resize "800>" ./originals/ansprechperson_003.jpg ./img/ansprechperson_003.jpg
convert -auto-level -normalize -resize "800>" ./originals/ansprechperson_004.jpg ./img/ansprechperson_004.jpg
convert -auto-level -normalize -resize "800>" ./originals/ol_zimmerberg_001.jpg ./img/ol_zimmerberg_001.jpg
convert -auto-level -normalize -resize "800>" ./originals/ol_zimmerberg_002.jpg ./img/ol_zimmerberg_002.jpg
convert -auto-level -normalize -resize "800>" ./originals/ol_zimmerberg_003.jpg ./img/ol_zimmerberg_003.jpg
convert -auto-level -normalize -resize "800>" ./originals/ol_zimmerberg_004.jpg ./img/ol_zimmerberg_004.jpg
convert -auto-level -normalize -resize "800>" ./originals/ol_zimmerberg_005.jpg ./img/ol_zimmerberg_005.jpg
convert -auto-level -normalize -resize "800>" ./originals/ol_zimmerberg_006.jpg ./img/ol_zimmerberg_006.jpg
convert -auto-level -normalize -resize "800>" ./originals/ol_zimmerberg_007.jpg ./img/ol_zimmerberg_007.jpg
convert -auto-level -normalize -resize "800>" ./originals/ol_zimmerberg_008.jpg ./img/ol_zimmerberg_008.jpg
convert -auto-level -normalize -resize "800>" ./originals/ol_zimmerberg_009.jpg ./img/ol_zimmerberg_009.jpg
convert -auto-level -normalize -resize "800>" ./originals/ol_zimmerberg_010.jpg ./img/ol_zimmerberg_010.jpg
convert -auto-level -normalize -resize "800>" ./originals/ol_zimmerberg_011.jpg ./img/ol_zimmerberg_011.jpg
convert -auto-level -normalize -resize "800>" ./originals/ol_zimmerberg_012.jpg ./img/ol_zimmerberg_012.jpg
convert -auto-level -normalize -resize "800>" ./originals/ol_zimmerberg_013.jpg ./img/ol_zimmerberg_013.jpg
convert -auto-level -normalize -resize "800>" ./originals/ol_zimmerberg_014.jpg ./img/ol_zimmerberg_014.jpg
convert -auto-level -normalize -resize "800>" ./originals/ol_zimmerberg_015.jpg ./img/ol_zimmerberg_015.jpg
convert -auto-level -normalize -resize "800>" ./originals/ol_zimmerberg_016.jpg ./img/ol_zimmerberg_016.jpg
convert -auto-level -normalize -resize "800>" ./originals/orientierungslauf_001.jpg ./img/orientierungslauf_001.jpg
convert -auto-level -normalize -resize "800>" ./originals/orientierungslauf_002.jpg ./img/orientierungslauf_002.jpg
convert -auto-level -normalize -resize "800>" ./originals/orientierungslauf_003.jpg ./img/orientierungslauf_003.jpg
convert -auto-level -normalize -resize "800>" ./originals/orientierungslauf_004.jpg ./img/orientierungslauf_004.jpg
convert -auto-level -normalize -resize "800>" ./originals/pack_die_chance_001.jpg ./img/pack_die_chance_001.jpg
convert -auto-level -normalize -resize "800>" ./originals/trainings_001.jpg ./img/trainings_001.jpg
convert -auto-level -normalize -resize "800>" ./originals/trainings_002.jpg ./img/trainings_002.jpg
convert -auto-level -normalize -resize "800>" ./originals/trainings_003.jpg ./img/trainings_003.jpg
convert -auto-level -normalize -resize "800>" ./originals/trainings_004.jpg ./img/trainings_004.jpg
convert -auto-level -normalize -resize "800>" ./originals/trainings_005.jpg ./img/trainings_005.jpg
convert -auto-level -normalize -resize "800>" ./originals/trainings_006.jpg ./img/trainings_006.jpg
convert -auto-level -normalize -resize "800>" ./originals/trainings_007.jpg ./img/trainings_007.jpg
convert -auto-level -normalize -resize "800>" ./originals/trainings_008.jpg ./img/trainings_008.jpg
convert -auto-level -normalize -resize "800>" ./originals/trainings_009.jpg ./img/trainings_009.jpg
convert -auto-level -normalize -resize "800>" ./originals/trainings_010.jpg ./img/trainings_010.jpg
convert -auto-level -normalize -resize "800>" ./originals/trainings_011.jpg ./img/trainings_011.jpg
convert -auto-level -normalize -resize "800>" ./originals/trainings_012.jpg ./img/trainings_012.jpg
convert -auto-level -normalize -resize "800>" ./originals/trainings_013.jpg ./img/trainings_013.jpg
convert -auto-level -normalize -resize "800>" ./originals/trainings_014.jpg ./img/trainings_014.jpg
convert -auto-level -normalize -resize "800>" ./originals/trainings_015.jpg ./img/trainings_015.jpg
convert -auto-level -normalize -resize "800>" ./originals/trainings_016.jpg ./img/trainings_016.jpg
convert -auto-level -normalize -resize "800>" ./originals/was_ist_ol_001.jpg ./img/was_ist_ol_001.jpg
convert -auto-level -normalize -resize "800>" ./originals/wie_anfangen_001.jpg ./img/wie_anfangen_001.jpg
convert -auto-level -normalize -resize "800>" ./originals/wie_anfangen_002.jpg ./img/wie_anfangen_002.jpg
convert -auto-level -normalize -resize "800>" ./originals/wie_anfangen_003.jpg ./img/wie_anfangen_003.jpg
convert -auto-level -normalize -resize "800>" ./originals/wie_anfangen_004.jpg ./img/wie_anfangen_004.jpg
