<?php

declare(strict_types=1);

namespace OLZ\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20220317172850 extends AbstractMigration {
    public function getDescription(): string {
        return 'Add quiz entities';
    }

    public function up(Schema $schema): void {
        $this->addSql('CREATE TABLE quiz_categories (id INT AUTO_INCREMENT NOT NULL, parent_category_id INT DEFAULT NULL, owner_user_id INT DEFAULT NULL, owner_role_id INT DEFAULT NULL, created_by_user_id INT DEFAULT NULL, last_modified_by_user_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, on_off INT DEFAULT 1 NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, last_modified_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX IDX_739C61542B18554A (owner_user_id), INDEX IDX_739C61545A75A473 (owner_role_id), INDEX IDX_739C61547D182D95 (created_by_user_id), INDEX IDX_739C61541A04EF5A (last_modified_by_user_id), INDEX name_index (name), INDEX parent_category_index (parent_category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE quiz_skill (id BIGINT AUTO_INCREMENT NOT NULL, owner_user_id INT DEFAULT NULL, owner_role_id INT DEFAULT NULL, created_by_user_id INT DEFAULT NULL, last_modified_by_user_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, on_off INT DEFAULT 1 NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, last_modified_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX IDX_A24E9DF72B18554A (owner_user_id), INDEX IDX_A24E9DF75A75A473 (owner_role_id), INDEX IDX_A24E9DF77D182D95 (created_by_user_id), INDEX IDX_A24E9DF71A04EF5A (last_modified_by_user_id), INDEX name_index (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE quiz_skills_categories (skill_id BIGINT NOT NULL, category_id INT NOT NULL, INDEX IDX_7289B4265585C142 (skill_id), INDEX IDX_7289B42612469DE2 (category_id), PRIMARY KEY(skill_id, category_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE quiz_skill_levels (id BIGINT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, skill_id BIGINT DEFAULT NULL, owner_user_id INT DEFAULT NULL, owner_role_id INT DEFAULT NULL, created_by_user_id INT DEFAULT NULL, last_modified_by_user_id INT DEFAULT NULL, value DOUBLE PRECISION NOT NULL, recorded_at DATETIME NOT NULL, on_off INT DEFAULT 1 NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, last_modified_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX IDX_6699B5F6A76ED395 (user_id), INDEX IDX_6699B5F65585C142 (skill_id), INDEX IDX_6699B5F62B18554A (owner_user_id), INDEX IDX_6699B5F65A75A473 (owner_role_id), INDEX IDX_6699B5F67D182D95 (created_by_user_id), INDEX IDX_6699B5F61A04EF5A (last_modified_by_user_id), INDEX user_skill_index (user_id, skill_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE quiz_categories ADD CONSTRAINT FK_739C6154796A8F92 FOREIGN KEY (parent_category_id) REFERENCES quiz_categories (id)');
        $this->addSql('ALTER TABLE quiz_categories ADD CONSTRAINT FK_739C61542B18554A FOREIGN KEY (owner_user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE quiz_categories ADD CONSTRAINT FK_739C61545A75A473 FOREIGN KEY (owner_role_id) REFERENCES roles (id)');
        $this->addSql('ALTER TABLE quiz_categories ADD CONSTRAINT FK_739C61547D182D95 FOREIGN KEY (created_by_user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE quiz_categories ADD CONSTRAINT FK_739C61541A04EF5A FOREIGN KEY (last_modified_by_user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE quiz_skill ADD CONSTRAINT FK_A24E9DF72B18554A FOREIGN KEY (owner_user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE quiz_skill ADD CONSTRAINT FK_A24E9DF75A75A473 FOREIGN KEY (owner_role_id) REFERENCES roles (id)');
        $this->addSql('ALTER TABLE quiz_skill ADD CONSTRAINT FK_A24E9DF77D182D95 FOREIGN KEY (created_by_user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE quiz_skill ADD CONSTRAINT FK_A24E9DF71A04EF5A FOREIGN KEY (last_modified_by_user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE quiz_skills_categories ADD CONSTRAINT FK_7289B4265585C142 FOREIGN KEY (skill_id) REFERENCES quiz_skill (id)');
        $this->addSql('ALTER TABLE quiz_skills_categories ADD CONSTRAINT FK_7289B42612469DE2 FOREIGN KEY (category_id) REFERENCES quiz_categories (id)');
        $this->addSql('ALTER TABLE quiz_skill_levels ADD CONSTRAINT FK_6699B5F6A76ED395 FOREIGN KEY (user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE quiz_skill_levels ADD CONSTRAINT FK_6699B5F65585C142 FOREIGN KEY (skill_id) REFERENCES quiz_skill (id)');
        $this->addSql('ALTER TABLE quiz_skill_levels ADD CONSTRAINT FK_6699B5F62B18554A FOREIGN KEY (owner_user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE quiz_skill_levels ADD CONSTRAINT FK_6699B5F65A75A473 FOREIGN KEY (owner_role_id) REFERENCES roles (id)');
        $this->addSql('ALTER TABLE quiz_skill_levels ADD CONSTRAINT FK_6699B5F67D182D95 FOREIGN KEY (created_by_user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE quiz_skill_levels ADD CONSTRAINT FK_6699B5F61A04EF5A FOREIGN KEY (last_modified_by_user_id) REFERENCES users (id)');
    }

    public function down(Schema $schema): void {
        $this->addSql('ALTER TABLE quiz_categories DROP FOREIGN KEY FK_739C6154796A8F92');
        $this->addSql('ALTER TABLE quiz_skills_categories DROP FOREIGN KEY FK_7289B42612469DE2');
        $this->addSql('ALTER TABLE quiz_skills_categories DROP FOREIGN KEY FK_7289B4265585C142');
        $this->addSql('ALTER TABLE quiz_skill_levels DROP FOREIGN KEY FK_6699B5F65585C142');
        $this->addSql('DROP TABLE quiz_categories');
        $this->addSql('DROP TABLE quiz_skill');
        $this->addSql('DROP TABLE quiz_skills_categories');
        $this->addSql('DROP TABLE quiz_skill_levels');
        $this->addSql('ALTER TABLE access_tokens CHANGE purpose purpose VARCHAR(255) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE token token VARCHAR(255) NOT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE aktuell CHANGE titel titel LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE text text LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE textlang textlang LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE image_ids image_ids LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE link link LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE autor autor VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE typ typ LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE bild1 bild1 LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE bild1_text bild1_text LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE bild2 bild2 LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE bild3 bild3 LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE anm_felder CHANGE label label LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE typ typ LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE info info LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE standard standard LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE test test LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE test_result test_result LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE anmeldung CHANGE event_id event_id VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE email email VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE uid uid VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE name name VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE feld1 feld1 LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE feld2 feld2 LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE feld3 feld3 LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE feld4 feld4 LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE auth_requests CHANGE ip_address ip_address VARCHAR(40) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE action action VARCHAR(31) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE username username LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE bild_der_woche CHANGE bild1 bild1 LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE bild2 bild2 LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE text text LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE titel titel LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE blog CHANGE autor autor LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE titel titel LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE text text LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE bild1 bild1 LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE bild2 bild2 LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE file1 file1 LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE file1_name file1_name LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE file2 file2 LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE file2_name file2_name LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE linkext linkext LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE counter CHANGE page page VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE date_range date_range VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE args args LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE downloads CHANGE name name LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE file1 file1 LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE event CHANGE name_kurz name_kurz VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE name name LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE kat_gruppen kat_gruppen LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE karten karten LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE facebook_links CHANGE access_token access_token LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE refresh_token refresh_token LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE facebook_user facebook_user LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE forum CHANGE name name VARCHAR(255) DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE email email VARCHAR(255) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE eintrag eintrag LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE uid uid VARCHAR(255) DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE name2 name2 VARCHAR(255) DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE galerie CHANGE titel titel LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE autor autor LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE typ typ LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE content content LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE google_links CHANGE access_token access_token LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE refresh_token refresh_token LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE google_user google_user LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE images CHANGE table_parent table_parent LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE pfad pfad LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE bild_name bild_name LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE jwoc CHANGE name name LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE nation nation VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE time1 time1 LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE time2 time2 LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE time3 time3 LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE time4 time4 LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE time5 time5 LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE diff diff LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE starttime starttime LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE cat cat LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE karten CHANGE name name VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE jahr jahr VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE massstab massstab VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE ort ort VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE typ typ VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE vorschau vorschau VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE links CHANGE name name LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE url url LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE notification_subscriptions CHANGE delivery_type delivery_type VARCHAR(255) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE notification_type notification_type VARCHAR(255) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE notification_type_args notification_type_args LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE olz_result CHANGE name name VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE club club VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE zeit zeit VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE kat kat VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE stand stand VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE anzahl anzahl VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE event event VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE olz_text CHANGE text text LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE roles CHANGE username username LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE old_username old_username LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE name name LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE description description LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci` COMMENT \'public\', CHANGE guide guide LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci` COMMENT \'restricted access\', CHANGE page page LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE solv_events CHANGE kind kind LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE day_night day_night LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE region region LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE type type LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE name name LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE link link LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE club club LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE map map LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE location location LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE start_link start_link LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE rank_link rank_link LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE solv_people CHANGE name name LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE birth_year birth_year LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE domicile domicile LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE solv_results CHANGE class class VARCHAR(15) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE name name VARCHAR(31) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE birth_year birth_year VARCHAR(3) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE domicile domicile VARCHAR(31) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE club club VARCHAR(31) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE splits splits LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE strava_links CHANGE access_token access_token LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE refresh_token refresh_token LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE strava_user strava_user LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE telegram_links CHANGE pin pin VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE telegram_chat_id telegram_chat_id VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE telegram_user_id telegram_user_id VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE telegram_chat_state telegram_chat_state LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE termine CHANGE titel titel LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE go2ol go2ol LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE text text LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE link link LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE solv_event_link solv_event_link LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE typ typ VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE text_anmeldung text_anmeldung LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE email_anmeldung email_anmeldung LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE ical_uid ical_uid VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE termine_go2ol CHANGE link link VARCHAR(255) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE ident ident VARCHAR(255) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE name name VARCHAR(255) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE post post VARCHAR(255) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE verein verein VARCHAR(255) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE datum datum VARCHAR(255) NOT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE termine_solv CHANGE kind kind VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE day_night day_night VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE region region VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE type type VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE event_name event_name VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE event_link event_link VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE club club VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE map map VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE location location VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE throttlings CHANGE event_name event_name VARCHAR(255) NOT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE trainingsphotos CHANGE name name LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE pfad pfad LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE users CHANGE username username VARCHAR(255) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE old_username old_username VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE password password LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE email email LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE email_verification_token email_verification_token LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE first_name first_name LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE last_name last_name LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE gender gender VARCHAR(2) DEFAULT NULL COLLATE `utf8mb4_unicode_ci` COMMENT \'M(ale), F(emale), or O(ther)\', CHANGE street street LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE postal_code postal_code LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE city city LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE region region LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE country_code country_code VARCHAR(3) DEFAULT NULL COLLATE `utf8mb4_unicode_ci` COMMENT \'two-letter code (ISO-3166-alpha-2)\', CHANGE phone phone LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE zugriff zugriff LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE root root LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');
    }
}
