<?php
$panini_data = array(
    array(1, "Unmöglich, sie alle aufzuzählen", "Die Vielfalt der Mitglieder macht die OLZ aus :-)", "Jeder (Wald-) OL ist für mich ein kleines Abenteuer :-)", ""),
    array(2, "Überlebender des Nat. OL Crap Sogn Gion 2014", "OL im Sihlwald", "Informer, junosydadymisnowmeagunablam a licky boom boom down", ""),
    array(3, "Klubreise nach Prag", "Sieg an der 5er-Staffel", "Es ist cool, dass wir ein Klubbüssli besitzen", ""),
    array(4, "Julia, Lilly und Paula gewinnen an der SOM 2012 in St. Moritz völlig überraschend den SM-Titel", "Ich träume von einer MOM im Sihlwald", "Ich finde es cool, dass wir so viele engagierte und kreative Leute im Verein haben!", ""),
    array(5, "Schlussphase der 5. Strecke an der 5er-Staffel 2008", "SPM in Gattikon mit Patent Ochsner als musikalische Unterstützung", "Ha - Halilu - Halilulilei", ""),
    array(6, "Jede Swiss-O-Week mit allem Drum und Dran", "Regelmässige OLZ-Reisen an ausländische Events", "Französisch ist doof", ""),
    array(7, "Weltmeisterin D60 Sprint 2010 in Neuchâtel", "Keine Meisterschaften und Nat. im Gebirge", "OLs ohne \"Abfahrten\" wären toll", ""),
    array(8, "Klubreise nach Prag", "Rückeroberung der JOM Club-Gesamtwertung", "OL sollte olympisch werden", ""),
    array(9, "Überaschungstag 2015 im Atzmännig", "Einmal auf den 1. Platz laufen", "Die OL Zimmerberg finde ich super", ""),
    array(10, "Scool Cup", "OL im Irchelpark", ":-)", ""),
    array(11, "Erster OL", "OL im irchelpark", "", ""),
    array(12, "Pfingststaffel 2015", "Viel Erfolg allne!", "Hallo!", ""),
    array(13, "OL-Lager 2015", "Jede Ferien ein OLZ-Lager", "Ich mag keine Wald-OLs", ""),
    array(14, "Morgendlicher Nacht-OL im Lager in Solothurn", "Weiterhin so viele tolle Kolleginnen und Kollegen", "OL ist ein verbindender Sport", ""),
    array(15, "Startweekend 2013", "Training auf einen anderen Tag verschieben", "Gnüsseds", ""),
    array(16, "Choche a de Pfingststaffle 2012", "Bliibet fit", "Saletti Spaghetti", ""),
    array(17, "OLZ gewinnt den an der SOM im Engadin im Herbst 2012 den Titel in der Elite mit Julia, Lilly und Paula!", "Durchführung der Sprint SM in Richterswil", "Kein OL-Club kann besser fanen als die OLZ!", ""),
    array(18, "Viel Lärm im OLZ-Büssli und a de Zieliläuf", "Viel Nachwuchs (ikauft oder selbsterzügt)", "Düend eui Fuessglänk guet trainiere und tape!!!", ""),
    array(19, "Clubreise Prag", "Machen wir weiter so und entwickeln immer wieder neue Ideen", "Mir sind eifach de bescht Verein!", ""),
    array(20, "OL-Lager Solothurn 2007", "Beitritt von Simon Jakob und Severin Denzler in die OL Zimmerberg", "Es wäre schön, wenn wir die 5er-Staffel 2016 gewinnen würden", ""),
    array(21, "Der Singabend im OL-Lager 2014", "Weiterhin eine so gute Stimmung untereinander", "Die OLZ sind der beste Club überhaupt!!!", ""),
    array(22, "OL-Lager 2015 in La Chaux-du-Milieu", "Viel Spass und Erfolg", "Don't be afraid to give up the good and go for the great", ""),
    array(23, "Poncho of the day in Pontresina", "Keine ernsthaften Verletzungen", "Heja Evi Zimmerzwerg", ""),
    array(24, "Rafzerfelder OL 2015, weil es mein 1. OL-Wettkampf war", "Ich möchte mich für das Kader qualifizieren", "Es ist cool das ich, als Neuling, so gut aufgenommen wurde", ""),
    array(25, "SOW Zermatt I + II", "Dass Kopf und Füsse noch lange durchhalten (meine)", "Jetzt haben wir auch noch ein staubfreies Materiallager :-) !", ""),
    array(26, "Beim letzten Wisliger quer durch den Wald rennen", "Noch mehr Mädchen in meinem Alter", "OL ist cool", ""),
    array(27, "Alpine OL-Leckerbissen bei Wind und Wetter", "Wo bleiben die 70er und 80er Jahrgänge?", "Join on www.strava.com/clubs/olzimmerberg", ""),
    array(28, "Swiss-O-Week in Flims-Laax 2011", "Das Ziel ohne Badge-Verlust erreichen!", "Wer einatmet muss auch wieder ausatmen", ""),
    array(29, "OLZ-Klubreise nach Prag 2012", "Eine OLZ-Klubhütte mit Sauna im Landforst!", "Zieleinläufe mit OLZ-Unterstützung machen Spass!", ""),
    array(30, "Den Vereins-Pokal in den Händen halten", "Im Zieleinlauf schneller sein als Mama und Papa!", "Ich freue mich auf mein erstes OL-Lager!", ""),
    array(31, "Mein erster OL im Wald mit Papa (Elsass 2015)!", "Dass alle OLZler immer alle Posten finden!", "Ich wünsche allen ein glückliches Leben!", ""),
    array(32, "OL-Lager in La Chaux-du-Milieu", "Weitere coole Ausflüge und Trainings", "Super, dass das Büssli immer ins Training fährt", ""),
    array(33, "Elsass", "Wenig Verletzte", "Ich bin unkreativ", ""),
    array(34, "Swiss-O-Week in Zermatt; Edi Bühler am Aargauer 3-Tage-OL wieder als Läufer gesehen zu haben", "Den bestehenden Drive aufrechterhalten und unsere Organisationstalente regelmässig in Szene setzen", "Unser Präsident ist grossartig", ""),
    array(35, "In meiner jungen OL-Karriere ist jeder OL der Schönste, bei dem ich alle Posten finde", "Dass der Verein auch weiterhin bei regionalen, nationalen und internationalen OLs grosse Erfolge feiern kann", "Cooler Verein", ""),
    array(36, "2x dä schnällscht Zürifuchs gewonnen", "Dass es weiterhin so coole Betreuer hat", "Es gefällt mir einfach in diesem Verein", ""),
    array(37, "Klubmeisterin 2014 zu werden", "Neue OL-Hosen", "Hopp OLZ!!", ""),
    array(38, "SOW Zermatt 06: das Gesamtpaket mit super Wetter", "Eine noch schönere SOW in St. Moritz", "Unsere OLZ-Beizen sind genial", ""),
    array(39, "Der Chlaus-OL 2014 in Zürich", "Weniger \"Truckete\" am Massenstart", "Meine OL-Schuhe könnten als Steine kartiert werden", ""),
    array(40, "SOW 2014: Etappe 3, Vorab", "Freud am OL ned verlüre", "Blib fit!", ""),
    array(41, "5er-Staffel in diesem Jahr als OLZ-Familienteam", "Ich wünsche mir viele grosse und kleine Läufer in grünem Dress an den OLs in der ganzen Schweiz", "Das verrate ich dir am nächsten OL", ""),
    array(42, "Die zwei SOM Siege der Gross-Schwestern", "Weiterhin so ein tolles Klubleben", "", ""),
    array(43, "Jukola-Staffel 2012 mit OLZ-Team", "GROSSes OLZ-Team holt an WM Staffel-Gold!", "OLZ = Nicht nur Posten finden, auch Frau fürs Leben!", ""),
    array(44, "Chlaus-OL 2014", "Einmal eine 5er-Staffel mit 15 Mannschaften", "Überholt mich nicht immer an den OLs!", ""),
    array(45, "Zermatt 2014", "Schnellere Zieleinläufe für alle", "Nur ZSC ist besser!", ""),
    array(46, "O-Ringen 2013", "Witerhin so lässigi gmeinsami Reise", "Au mir macht OL mängisch Spass", ""),
    array(47, "D' Zieliläuf mit heftigem Kuehgloggägebimmel", "Witerhin so tollä Clubgäischt", "Ich bin stolz uf mis grün-gälb-schwarzä Shört", ""),
    array(48, "SOW Zermatt, Trockener Steg", "100 mal OLZauber", "S'n'OL'n'R'n'R", ""),
    array(49, "SOW 2014 in Zermatt auf der Etappe auf dem Gornergrat von Posten 4 zum Posten 5", "Nach dem Militär wieder im Training zu erscheinen", "🌲🌲🌲🏃🌲🌲🌲", ""),
    array(50, "Aich gits zwai: Mini Saison 2015 + jedi 5er-Staffle :-)", "Witerhin sonen tolle unterstützende und grossartige fänende OL-Klub z'blibe!", "Ich träge mit Stolz grüen-gäll-schwarz ;-)", ""),
    array(51, "Die ganze O-Ringen-Reise mit der OLZ nach Boden, Schweden im 2013", "Weiterhin Plausch am OL haben", "Macht weiter so!!", ""),
    array(52, "Da gibt es zu viele für einen einzigen Kandidaten", "Besser werden", "Ich schätze das grosse Engagement der zahlreichen freiwilligen Helfer", ""),
    array(53, "SOW Flims und Zermatt", "Chris in der JOM-Wertung schlagen", "If the facts don't fit the theory, change the facts (A. Einstein)", ""),
    array(54, "Elsass 2015", "Gsund bliibe", "Danke! :D", ""),
    array(55, "ANKUNFT im WKZ nach dem Nat. OL im Crap (2014)", "Ein Sieg an der Klubmeisterschaft und am Chlaus-OL", "Ein Wald, ein Verein!", ""),
    array(56, "Clubreise nach Prag/Tschechien 2012", "Viele spannende OL-Erlebnisse", "OLZ ist ein toller Club mit super Mitgliedern", ""),
    array(57, "Sieg bim 24. Dietiker OL 2014 - vor 6 Gägner ...3 devo händ ufgäh", "Das d'Orientierig nie verlore gaht", "Nämed am Start immer di richtig Charte!", ""),
    array(58, "Chaotische aber doch noch erfolgreiche Postensuche bei der 5er-Staffel 2015", "200 TeilnehmerInnen am Chlausanlass 2025", "Danke für die sehr ideenreiche Nachwuchsarbeit!", ""),
    array(59, "Überraschigstag 2015 und Scool-Cup 2015", "En Sieg binere 5er-Staffle - mit mir als Schlussläufer ;-)", "Du Dani, wie viel Yoghurt-Chüe hämmer scho im Stall?", ""),
    array(60, "1. Platz bim Zürcher OL 2015", "Vill Wald-OL und nöd so vill Stadt-OL", "Ich freu mich uf d'Paninibildli!", ""),
    array(61, "OL Melchseefrutt / Klausenpass", "Einmal einen OL organisieren mit dem Motto \"3 Sprints in 3 Ortschaften an einem Tag\"", "Die Trainings sind super, lässig, einmalig, toll, einzigartig, mega, spannend und lehrreich", ""),
    array(62, "Klubreise an Mehrtage-OL in Prag", "Noch viele schöne Klubreisen", "Auch wenn ich die Posten nicht immer auf anhin finde, OL macht Spass", ""),
    array(63, "Die SOW 2014 in Zermatt und die Klubreise ins Elsass 2015", "Weiterhin viele schöne und erfolgreiche gemeinsame Wettkämpfe und Reisen", "Irgendwann gewinnen die OL Zimmerberg die 5er-Staffel...", ""),
    array(64, "Pfista 2014, mini erst Pfista überhaupt und s'erscht mal im grüene Tenue", "A allne Pfistas und 5er-Staffle chöne mitmache", "Danke, dass au mir Lozärner i euem Verein willkomme sind!!", ""),
    array(65, "Wenn die OL-Lager-Kinder mit Freude essen", "Weiterhin eine so gute Kinder- und Jugendförderung", "Die OL Zimmerberg hat die coolsten Kids und die tollsten Leiter!", ""),
    array(66, "OL-Lager 2015, als ich endlich im Ziel ankam", "Dass es weiterhin so viel Spass macht wie schon immer", "Us Prinziip eifach so", ""),
    array(67, "Im eigenen XSSS-Dress am Kinder-OL zu starten", "Dass ich auch bald ins OL-Lager gehen darf...", "Danke für die vielen Schulhaus-OLs mit Sportident", ""),
    array(68, "Alle OLZ-Samichlaus-Events", "Dass ich auch bald ins OL-Lager gehen darf...", "Schulhaus-OL mit Preisen ist mega lässig. Danke!", ""),
    array(69, "Swiss-O-Week 2006 Zermatt", "Klubreise in den Norden", "Ich bin stolz aufs gute Nachwuchsbetreuungsteam", ""),
    array(70, "Clubreise nach Prag", "OL-Projekte in anspruchsvollen Wäldern", "Danke Jungs für die Weitergabe der OL-Begeisterung", ""),
    array(71, "Velikonoce ve skalàch (Prag Ostern 2012) und Valio-Jukola (Finnland 2012)", "Viele coole Staffeln mit vielen OLZ-Teams", "Gäbe es die OL Zimmerberg nicht, müsste man sie erfinden", ""),
    array(72, "Klubreis nach Prag", "Viil Spass und Erfolg mitenand", "Dä Klubgeist isch genial", ""),
    array(73, "SPM Dornbirn", "Dass meine OLZ-Karriere noch 10 Jahre dauert", "OL isch gsund und git ä guäti Lunä (bi schönem Wätter)", ""),
    array(74, "SOW 2011 im Laaxer Haus", "Weiter so", "Bin stolz eine Zimmerberglerin zu sein", ""),
    array(75, "Rangverkündigung Elsass 2015 + OL-Lager", "Weiterhin so eine lässige Gruppe", "Der beste Klub!", ""),
    array(76, "Morgenstimmung in Braunwald", "OL bleibt für jung und alt die Trendsportart", "Tragt Sorge zur Umwelt", ""),
    array(77, "Als mich der Samichlaus nicht in den Sack genommen hat", "Viele Nachwuchsläufer", "(Wenn ich etwas sagen will dann sage ich es)", ""),
    array(78, "10x 5er-Staffel", "10x10 Teams an der 5er-Staffel", "Was wäre die 5er-Staffel ohne die OL Zimmerberg?", ""),
    array(79, "OL-Ostern in Tschechien", "Viele kleine Kinder ... Nachwuchs", "Super motivierte Trainer", ""),
    array(80, "Schlusslaufweekend 2015", "Mehr JOM Läufe", "Zeichnet die Karte richtig ab", ""),
    array(81, "\"Vogel-Lauf\" mit Chiara", "Viele JOM-Siege meiner Enkel", "Wenn ich etwas sagen will sage ich es sofort - Mached wiiter so!", ""),
    array(82, "Clubreise Prag", "Sieg an der 5er-Staffel", "Ich plane mein Comeback", ""),
    array(83, "Chlausabend in Richterswil, Nachtessen im Kirchgemeindehaus", "OL bleibt ein Spass für jung und alt, Gross und ... die andern", "Nicht hasten, aber auch nicht rasten - Beides kann die OL-Freude belasten", ""),
    array(84, "Überraschende Vize-SOM-Titel mit mine Schwöschtere", "Wiiterhin vill Chind mit OL glücklich mache", "Au Ü30 OLZler därfed HOLZ-Bricht schribe", ""),
    array(85, "Schlusslaufweekend 2015", "Cooli Trainings", "Tolli Leiter", ""),
    array(86, "SOW Zermat 2006", "Dass Knie, und was sonst noch dazu gehört, halten", "Pandoro und Panettone sind 2 ganz verschiedene italienische Süssspeisen", ""),
    array(87, "Alli OL-Lagers", "Das es am Verein au witer so guet gat", "Blibet gsund!", ""),
    array(88, "Komplimente für mein Pilz-Risotto an der Pfingststaffel", "Noch viele schöne Pfingststaffeln", "Bike-OL igugegl!", ""),
    array(89, "Gründungsversammlung als die Fusion (endlich) geklappt hat", "Fadegrad so weiter", "Danke für die tollen Erlebnisse in den (4: KaKoWa, Thalwil, Horgen) linksufrigen OLGs!", ""),
    array(90, "2. OLZ-Sprintmeisterschaft 2012. Dieser Anlass war spannend und vergnüglich. Die Regengüsse rundeten die gelungene Veranstaltung ab", "Die ersten schönen 10 Jahre wiederholen", "Die OLZ ist weltweit der beste OL-Club mit den nettesten OL-Läuferinnen und -Läufern", ""),
    array(91, "Klubreise Prag, Vize-SM 2014 (leider nicht im OL)", "Viele innovative, coole OL-Ideen wie Panini, etc.", "Wie wär's einmal mit einem Indoor-OL mit 3. Dimension?", ""),
    array(92, "Erster Longjogg 2016 bei Thomas", "Weiterhin so eine fröhliche, von jung bis alt durchmischte Bande zu sein mit vielen engagierten Mitgliedern und Trainern", "Danke vielmals für's herzliche Willkommenheissen und das sofortige Aufnehmen in diesen tollen Verein!", ""),
    array(93, "Ränne", "Wänn ich 15i bin uf e OL-Reis gah", "Dass ali Bäum Velofahred", ""),
    array(94, "Stäckli sammle", "Päckli sammle", "Blättlimatsch", ""),
    array(95, "", "", "", ""),
    array(96, "Zieleinlauf vo de 5er-Staffle 2015", "Ab 2017: Immer mind. je 1 OLZ Jukola- und Venla-Team pro Usträgig", "Mit Isostar gahts nöd besser aber länger", ""),
    array(97, "Bezirks-Longjogg 2014", "Einen nutzbaren, schönen und anspruchsvollen Wald", "Beeindruckender Zusammenhalt in einem Verein, der über eine ganze Region verteilt ist und jede Aktivität einen enormen Aufwand bedeutet", ""),
    array(98, "OL-Lager 2015 oder doch eher O-Ringen 2013? Weiss nicht!", "Dass ich wieder OL machen werde!", "Freiheit für den Sihlwald!", ""),
    array(99, "XXXII Meeting Internazionale di Corsa Orientamento Venezia", "Einen Wettkampf in meinem Lieblingspilzwald in Ftan", "Mein Ziel: SOLA DUO mit Dani erfolgreich absolvieren", ""),
    array(100, "Nacht-OL im Landforst", "Das ich mal 1. werde in meiner Kategorie", "Die OL Zimmerberg ist super", ""),
    array(101, "Hallentraining bei Jan", "In möglichst viele OL-Lager gehen", "OL macht Spass", ""),
    array(102, "Sieg im Kühlevölk im Halletraining", "Dass es mir weiterhin so viel Spass macht im OL", "Der FC Barcelona ist mein Lieblingsfussballverein", ""),
    array(103, "S Tümpel-Bad im OL-Lager z Mannebach", "Villi wiiteri kuuli Team-OLs", "Oisi OL-Dress Kollektion isch eimalig", ""),
    array(104, "Wo ich im Lager 2-ter wurde", "Bei JOM-Läufen immer unter die ersten 10 Plätze kommen", "Wie viele sind die OLZ?", ""),
    array(105, "Kommt wohl noch...", "Gsund bliibe", "OL-Saison bis in den Dezember verlängern", ""),
    array(106, "Klubreise Tschechien", "Eine Klubreise. (z.B. in den Süden im Februar)", "Danke OLZ <3", ""),
    array(107, "Jubiläumsreise Prag", "Gute Gesundheit", "OLZ ist der geilste Orientierungsverein der Welt", ""),
    array(108, "Jura 3er Staffle", "neues Dress", "", ""),
    array(109, "Fleischchäs an der GV", "Begegnung mit dem Wolf", "Weg mit den Dornen!", ""),
    array(110, "Papiersammle", "", "Will Baum", ""),
    array(111, "Leiteressen Tesserete", "An den Meisterschaften viele OLZ-Teams", "Mehr Trainings mit anderen Clubs", ""),
    array(112, "Mein Comeback nach 30 Jahren OL-Abstinenz", "Viele neue Wälder, Karten und Läufe", "Geniale Nachwuchsförderung", ""),
    array(113, "Klubmeisterschaft 2015", "Wieder an der SOW laufen", "Di deusche gramaatik mag i nied", ""),
    array(114, "Das organisieren des OLs in Braunwald", "Weiterhin so einen motivierten Verein zu haben", "Der beste Verein, den es gibt", ""),
    array(115, "Ich bin noch nicht allzu lange mit von der Partie, aber habe schon eine recht intensive Zeit mit dem Verein verbracht. Top Erlebnis wäre zum Beispiel die Reise ins Elsass", "Die OLZ sind ein sehr spezieller Orientierungslauf-Verein mit speziellen und innovativen Ideen und grossartiger Fankultur, ob im Amateurbereich oder bei der Elite. Ich hoffe, dass dieser spezielle Charakter des ganzen Clubs beibehalten wird und die ganze OL-Schweiz verzaubert", "HAL Konkurrenz für eine Saison aus den OLZ gesucht", ""),
    array(116, "Stadt-OLs", "mit der ganzen OLZ ins Hallenbad", "OL ist lustig", ""),
    array(117, "Ich kann mich nicht entscheiden, es gab viele Highlights", "Ich wünsche mir, dass die OLZ so bleiben wie sie sind", "Yeehaa", ""),
    array(118, "Das OL-Lager 2015, weil es sehr Spass gemacht hat", "Ich möchte viele Wettkämpfe mitmachen", "OL mach mir RIESENSPASS", ""),
    array(119, "Mein erster richtiger OL draussen: Klubmeisterschaft 2012 auf dem Albis", "Mehr an OLs teilzunehmen", "", ""),
    array(120, "Erstes OL-Lager 2015", "An mehr Trainings teilnehmen", "Es macht mega Spass bei den OL Zimmerberg dabei zu sein", ""),
    array(121, "Chlaus-OL 2015", "Dass ich gleich gut werde wie Judith Wyder", "Ich finde das Paninialbum eine sehr tolle Idee", ""),
    array(122, "Die Trainingslager als Leiter mit dem Nationalkader in der Tschechei und Ungarn in den 1980er", "Dass mir ENDLICH wieder einmal ein OL ohne stupide Kartenfehler gelingt", "Was in den letzten Jahren mit den OLZ aus der Fusion von OLG Thalwil und OLG Horgen entstanden ist, ist grossartig. Ein dickes Bravo allen Verantwortlichen", ""),
    array(123, "Nacht-OL Meisterschaft in Tschechien", "Wieder in eine gute Form kommen =)", "", ""),
    array(124, "Wintertrainingslager in Tschechien", "bessere Arbeit mit der Karte", "", ""),
    array(125, "Letzter Posten der OLZ-Klubreise in Tschechien (endlich das Ziel in Sicht & tosende OLZ- Unterstützung trotz eisigem Schneetreiben).", "Es gibt neben den OLZ nur noch einen \"Z\", für den mein Herz höher schlägt (\"dä links vo dä Gleis\")", "", ""),
);
do {
$rand_person = $panini_data[rand()%count($panini_data)];
$r_mode = rand()%3;
$modes = array(
    0=>"Mein bestes OLZ-Erlebnis",
    1=>"Mein Wunsch für die nächsten 10 OLZ-Jahre",
    2=>"Was ich schon immer sagen wollte",
);
$rand_mode = $modes[$r_mode];
} while (strlen($rand_person[$r_mode+1])==0);
echo "<div style='".(isset($_SESSION["auth"])?"":"display:none;")." padding-bottom:10px; background-color:#D4E7CE; padding:10px 20px; margin:25px 0px; border-bottom:1px solid #007521; border-top:1px solid #007521' id='panini2016'>";
echo "<center><table style='width:auto;'><tr><td><img src='olz_mitglieder/panini2016/".str_pad($rand_person[0], 3, "0", STR_PAD_LEFT).".png' style='margin:-30px 10px -30px 0px; border:0px;' /></td><td style='vertical-align:middle;'>";
echo "<div style='font-weight:bold; font-size:16px; line-height:1.5em;'>".$rand_mode.":</div>";
echo "<div style='font-style:italic; font-size:16px; line-height:1.5em;'>".$rand_person[$r_mode+1]."</div>";
echo "</td></tr></table></center></div>";
?>
