on:
  workflow_dispatch:
  push:
    branches:
      - main

name: CI:prod

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:

  take-screenshots:
    strategy:
      matrix:
        slice: ['1', '2', '3']
    name: Take screenshots (${{ matrix.slice }}/3)
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:11.2
        ports:
          - 3306
        env:
          MYSQL_USER: db-username
          MYSQL_PASSWORD: db-password
          MYSQL_DATABASE: db-schema
          MYSQL_ROOT_PASSWORD: db-password
        options: --health-cmd="mariadb-admin ping" --health-interval=5s --health-timeout=2s --health-retries=3
    steps:
    - uses: actions/checkout@v3
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
    - name: Install symfony-cli
      # https://symfony.com/download
      run: |
        curl -sS https://get.symfony.com/cli/installer | bash; mv /home/runner/.symfony5/bin/symfony /usr/local/bin/symfony
    - name: Get PHP (composer) cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
    - name: Cache PHP (composer) dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composerdev-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composerdev-
    - name: Install PHP (composer) dependencies
      run: composer install --prefer-dist
    - name: Get JavaScript (npm) cache directory
      id: npm-cache
      run: echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT
    - name: Cache JavaScript (npm) dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install JavaScript (npm) dependencies
      run: npm install
    - name: Take Screenshots
      env:
        DB_PORT: ${{ job.services.mariadb.ports[3306] }}
        MOZ_HEADLESS: 1
      run: composer system_tests -- --dev_rw ${{ matrix.slice }}/3
    - uses: actions/upload-artifact@v4
      with:
        name: prod-screenshots-${{ matrix.slice }}
        path: ./screenshots

  run-tests:
    strategy:
      matrix:
        php-version: ['8.2'] # 8.2 is active on hosting
    name: Tests (PHP ${{ matrix.php-version }})
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    services:
      mariadb:
        image: mariadb:11.2
        ports:
          - 3306
        env:
          MYSQL_USER: db-username
          MYSQL_PASSWORD: db-password
          MYSQL_DATABASE: db-schema_test
          MYSQL_ROOT_PASSWORD: db-password
        options: --health-cmd="mariadb-admin ping" --health-interval=5s --health-timeout=2s --health-retries=3
    steps:
    - uses: actions/checkout@v3
    - uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
    - name: Install symfony-cli
      # https://symfony.com/download
      run: |
        curl -sS https://get.symfony.com/cli/installer | bash; mv /home/runner/.symfony5/bin/symfony /usr/local/bin/symfony
    - name: Get PHP (composer) cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
    - name: Cache PHP (composer) dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composerdev-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composerdev-
    - name: Install PHP (composer) dependencies
      run: composer install --prefer-dist
    - name: Get JavaScript (npm) cache directory
      id: npm-cache
      run: echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT
    - name: Cache JavaScript (npm) dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install JavaScript (npm) dependencies
      run: npm install
    - name: Cache other caches
      uses: actions/cache@v3
      with:
        path: |
          *.cache
        key: ${{ runner.os }}-other-${{ hashFiles('*.cache') }}
        restore-keys: |
          ${{ runner.os }}-other-
    - name: PHP Code style check
      run: composer fixdiff
    - name: PHP Static Analysis
      run: composer check
    - name: Lint JavaScript & TypeScript
      run: npm run eslint
    - name: Lint CSS & SCSS
      run: npm run stylelint
    - name: Compile TypeScript
      run: npm run tsc
    - name: Jest Unit Tests
      run: composer jest_tests -- --runInBand
    - name: PHP Unit Tests
      run: composer unit_tests; cat ./php-coverage/coverage.txt || echo "no coverage!"
    - name: PHP Integration Tests
      env:
        DB_PORT: ${{ job.services.mariadb.ports[3306] }}
      run: composer integration_tests; cat ./php-coverage/coverage.txt || echo "no coverage!"
    - name: Check database migrations
      run: composer check_migrations
    - name: Setup GitHub Pages
      uses: actions/configure-pages@v5
    - name: Upload GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: './docs'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

  deploy-prod:
    name: Deploy to olzimmerberg.ch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
    - name: Get PHP (composer) cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
    - name: Cache PHP (composer) dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-
    - name: Install PHP (composer) dependencies
      run: composer install --no-dev --prefer-dist --optimize-autoloader
    - name: Get JavaScript (npm) cache directory
      id: npm-cache
      run: echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT
    - name: Cache JavaScript (npm) dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install JavaScript (npm) dependencies
      run: npm install
    - name: Deploy
      env:
        USERNAME: ${{ secrets.PROD_HOSTTECH_FTP_USERNAME }}
        PASSWORD: ${{ secrets.PROD_HOSTTECH_FTP_PASSWORD }}
        BOT_ACCESS_TOKEN: ${{ secrets.OLZ_BOT_TOKEN_PROD }}
      run: php ./Deploy.php --target=hosttech --environment=prod --username="$USERNAME"

  upload-screenshots:
    name: Upload screenshots to olzimmerberg.ch
    runs-on: ubuntu-latest
    needs: [deploy-prod, take-screenshots]
    steps:
    - uses: actions/checkout@v3
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
    - uses: actions/download-artifact@v4
      with:
        pattern: prod-screenshots-*
        merge-multiple: true
        path: ./screenshots
    - name: Get PHP (composer) cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
    - name: Cache PHP (composer) dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-
    - name: Install PHP (composer) dependencies
      run: composer install --no-dev --prefer-dist --optimize-autoloader
    - name: Upload over FTPS
      env:
        USERNAME: ${{ secrets.PROD_HOSTTECH_FTP_USERNAME }}
        PASSWORD: ${{ secrets.PROD_HOSTTECH_FTP_PASSWORD }}
      run: php ./ci/screenshot-upload.php --target=hosttech --environment=prod --username="$USERNAME"
