on:
  schedule:
    # daily at 13:49
    - cron:  '49 13 * * *'
name: CI:scheduled
jobs:
  fetch:
    name: HTTP fetch
    runs-on: ubuntu-latest
    steps:
    - name: olzimmerberg.ch
      run: wget -O - https://olzimmerberg.ch
    - name: test.olzimmerberg.ch
      run: wget -O - https://test.olzimmerberg.ch
