on:
  schedule:
    # daily at X:49
    - cron:  '49 * * * *'
name: CI:scheduled
jobs:

  fetch:
    name: HTTP fetch
    runs-on: ubuntu-latest
    steps:
    - name: olzimmerberg.ch
      run: wget -O - https://olzimmerberg.ch
    - name: test.olzimmerberg.ch
      run: wget -O - https://test.olzimmerberg.ch

  backup:
    name: Backup
    runs-on: ubuntu-latest
    steps:
    - name: Create backup
      run: mkdir backup; wget -O backup/prod.sql.crypt.json https://olzimmerberg.ch/tools.php/get-database-backup
    - name: Store backup
      uses: actions/upload-artifact@v2
      with:
        name: backup
        path: backup/*

  run-tests:
    strategy:
      matrix:
        php-version: ['8.1'] # 8.1 is active on hosting
    name: Tests (PHP ${{ matrix.php-version }})
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
    - name: Get composer cache directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composerdev-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composerdev-
    - name: Install dependencies
      run: composer install --dev --prefer-dist
    - name: PHP System Tests
      env:
        MOZ_HEADLESS: 1
      run: composer system_tests
