on:
  schedule:
    # daily at 13:49
    - cron:  '49 13 * * *'
name: CI:scheduled
jobs:

  fetch:
    name: HTTP fetch
    runs-on: ubuntu-latest
    steps:
    - name: olzimmerberg.ch
      run: wget -O - https://olzimmerberg.ch
    - name: test.olzimmerberg.ch
      run: wget -O - https://test.olzimmerberg.ch

  backup:
    name: Backup
    runs-on: ubuntu-latest
    steps:
    - name: Create backup
      run: mkdir backup; wget -O backup/prod.sql.crypt.json https://olzimmerberg.ch/tools.php/get-database-backup
    - name: Store backup
      uses: actions/upload-artifact@v2
      with:
        name: backup
        path: backup/*
