on:
  push:
    branches-ignore:
      - master
name: CI:test
jobs:
  take-screenshots:
    name: Take screenshots
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306
        env:
          MYSQL_USER: db-username
          MYSQL_PASSWORD: db-password
          MYSQL_DATABASE: db-schema
          MYSQL_ROOT_PASSWORD: db-password
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
    steps:
    - uses: actions/checkout@v2
    - uses: shivammathur/setup-php@v1
      with:
        php-version: '7.4'
    - name: Get composer cache directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-
    - name: Install dependencies
      run: composer install --prefer-dist
    - name: Get npm cache directory
      id: npm-cache
      run: |
        echo "::set-output name=dir::$(npm config get cache)"
    - uses: actions/cache@v1
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install JavaScript dependencies
      run: npm install
    - name: Take Screenshots
      env:
        DB_PORT: ${{ job.services.mariadb.ports[3306] }}
        MOZ_HEADLESS: 1
      run: ./integration-test.sh
    - uses: actions/upload-artifact@v1
      with:
        name: test-screenshots
        path: ./screenshots
  run-screenshot-tests:
    name: Screenshot tests
    runs-on: ubuntu-latest
    needs: take-screenshots
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v1
      with:
        name: test-screenshots
        path: ./ci/screenshots
    - uses: shivammathur/setup-php@v1
      with:
        php-version: '7.4'
    - name: Test screenshots for modifications
      run: cd ./ci; php ./screenshot-modifications.php
  run-php-tests:
    strategy:
      matrix:
        php-version: ['7.4'] # 7.4 is active on hosting
    name: PHP tests (PHP ${{ matrix.php-version }})
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: shivammathur/setup-php@v1
      with:
        php-version: ${{ matrix.php-version }}
    - name: Get composer cache directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-
    - name: Install dependencies
      run: composer install --prefer-dist
    - name: Lint PHP
      run: cd ./ci; ./php-lint.sh
    - name: Indented with spaces
      run: cd ./ci; ./php-indent-spaces.sh
    - name: Code style check
      run: cd ./ci; ./php-code-style.sh
    - name: PHP Unit Tests
      run: cd ./ci; ./php-unit-tests.sh
  deploy-test:
    name: Deploy to test.olzimmerberg.ch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get npm cache directory
      id: npm-cache
      run: |
        echo "::set-output name=dir::$(npm config get cache)"
    - uses: actions/cache@v1
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install JavaScript dependencies
      run: npm install
    - name: Build deployment
      run: ./build-deployment.sh
    - name: Deploy over SFTP
      env:
        SSHPASS: ${{ secrets.TEST_FTP_PASSWORD }}
      run: sshpass -e sftp -o StrictHostKeyChecking=no -P 5544 deploytest.olzimmerberg.ch@lx7.hoststar.hosting < ./ci/ftp-deploy
    - name: Activate deployment
      run: wget -O - https://test.olzimmerberg.ch/deploy/deploy.php
    - name: Load dev data
      run: wget -O - https://test.olzimmerberg.ch/reset.php
  upload-screenshots:
    name: Upload screenshots to test.olzimmerberg.ch
    runs-on: ubuntu-latest
    needs: [deploy-test, take-screenshots]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v1
      with:
        name: test-screenshots
        path: ./screenshots
    - name: Upload over SFTP
      env:
        SSHPASS: ${{ secrets.TEST_FTP_PASSWORD }}
      run: sshpass -e sftp -o StrictHostKeyChecking=no -P 5544 deploytest.olzimmerberg.ch@lx7.hoststar.hosting < ./ci/ftp-upload-screenshots
