on: push
name: Run tests
jobs:
  run-php-tests:
    name: PHP tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: shivammathur/setup-php@v1
      with:
        php-version: '7.4'
    - name: Lint PHP
      run: cd ./tests; ./php-lint.sh
    - name: Indented with spaces
      run: cd ./tests; ./php-indent-spaces.sh
