on: push
name: Run tests
jobs:
  deploy-test:
    name: Lint all *.php files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: shivammathur/setup-php@v1
      with:
        php-version: '7.4'
    - run: cd ./tests; ./php-lint.sh
